import { Product } from "./types";

/**
 * Sample catalog so the storefront is fully browsable before Supabase is
 * connected. Once NEXT_PUBLIC_SUPABASE_URL / ANON_KEY are set and products
 * exist in the `products` table, lib/products.ts serves those instead.
 *
 * Image URLs are left empty on purpose — no stock photos are bundled.
 * <ProductImage> renders an elegant placeholder swatch until the admin
 * uploads real photos to Supabase Storage.
 */
export const sampleProducts: Product[] = [
  {
    id: "p1",
    slug: "cloud-knit-romper",
    name: "Cloud Knit Romper",
    description:
      "A featherlight knit romper in brushed organic cotton, finished with mother-of-pearl buttons and a hand-smocked yoke. Made for naps, tummy time, and everything in between.",
    price: 185,
    discountPrice: null,
    category: "Newborn",
    subcategory: "Rompers",
    ageGroup: "0–3 months",
    sizes: ["Preemie", "Newborn", "0–3M"],
    colors: ["Sage", "Cream"],
    stock: 14,
    sku: "TTC-NB-001",
    status: "active",
    weightGrams: 120,
    images: [{ url: "", alt: "Cloud Knit Romper in sage" }],
    tags: ["organic cotton", "newborn", "gift-ready"],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
  },
  {
    id: "p2",
    slug: "heirloom-linen-dress",
    name: "Heirloom Linen Dress",
    description:
      "A relaxed linen dress with a hand-embroidered collar and delicate gold-thread trim. Pairs beautifully with our matching headband for special occasions.",
    price: 245,
    discountPrice: 199,
    category: "Dresses",
    subcategory: "Occasion",
    ageGroup: "1–3 years",
    sizes: ["12M", "18M", "2T", "3T"],
    colors: ["Beige", "Blush"],
    stock: 8,
    sku: "TTC-DR-014",
    status: "active",
    weightGrams: 180,
    images: [{ url: "", alt: "Heirloom Linen Dress in beige" }],
    tags: ["linen", "occasion wear", "sale"],
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: "p3",
    slug: "little-gent-two-piece",
    name: "Little Gent Two-Piece Set",
    description:
      "A tailored shirt and shorts set in soft sage poplin, with tortoiseshell buttons and a fully lined waistband for all-day comfort.",
    price: 210,
    discountPrice: null,
    category: "Baby Boys",
    subcategory: "Matching Sets",
    ageGroup: "1–4 years",
    sizes: ["12M", "2T", "3T", "4T"],
    colors: ["Sage", "White"],
    stock: 20,
    sku: "TTC-BB-022",
    status: "active",
    weightGrams: 210,
    images: [{ url: "", alt: "Little Gent two-piece set in sage" }],
    tags: ["matching set", "special occasion"],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
  },
  {
    id: "p4",
    slug: "golden-hour-jumpsuit",
    name: "Golden Hour Jumpsuit",
    description:
      "A breezy sleeveless jumpsuit with a golden thread trim along the neckline and covered snap closures for easy changes.",
    price: 175,
    discountPrice: null,
    category: "Baby Girls",
    subcategory: "Jumpsuits",
    ageGroup: "6–24 months",
    sizes: ["6–12M", "12–18M", "18–24M"],
    colors: ["Cream", "Gold"],
    stock: 16,
    sku: "TTC-BG-009",
    status: "active",
    weightGrams: 140,
    images: [{ url: "", alt: "Golden Hour Jumpsuit in cream" }],
    tags: ["summer", "gift-ready"],
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
  },
  {
    id: "p5",
    slug: "meadow-matching-set",
    name: "Meadow Sibling Matching Set",
    description:
      "Coordinating sage-and-cream separates designed to be mixed across siblings — because the best photos happen when everyone matches, just a little.",
    price: 260,
    discountPrice: 220,
    category: "Matching Sets",
    subcategory: "Sibling Sets",
    ageGroup: "1–5 years",
    sizes: ["2T", "3T", "4T", "5"],
    colors: ["Sage", "Cream", "Beige"],
    stock: 6,
    sku: "TTC-MS-004",
    status: "active",
    weightGrams: 260,
    images: [{ url: "", alt: "Meadow sibling matching set" }],
    tags: ["sibling set", "sale", "photoshoot ready"],
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: "p6",
    slug: "first-steps-mary-janes",
    name: "First Steps Mary Janes",
    description:
      "Buttery-soft leather Mary Janes with a flexible non-slip sole built for wobbly first steps, finished with a soft gold buckle.",
    price: 145,
    discountPrice: null,
    category: "Shoes",
    subcategory: "Mary Janes",
    ageGroup: "9–24 months",
    sizes: ["3", "4", "5", "6"],
    colors: ["Cream", "Beige"],
    stock: 22,
    sku: "TTC-SH-031",
    status: "active",
    weightGrams: 90,
    images: [{ url: "", alt: "First Steps Mary Janes in cream" }],
    tags: ["leather", "first walker"],
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: "p7",
    slug: "sage-bow-headband-set",
    name: "Sage Bow Headband Trio",
    description:
      "Three hand-tied bow headbands in sage, cream, and soft gold — stretch-knit bands that never leave a mark.",
    price: 65,
    discountPrice: null,
    category: "Accessories",
    subcategory: "Headbands",
    ageGroup: "0–24 months",
    sizes: ["One Size"],
    colors: ["Sage", "Cream", "Gold"],
    stock: 30,
    sku: "TTC-AC-007",
    status: "active",
    weightGrams: 40,
    images: [{ url: "", alt: "Sage bow headband trio" }],
    tags: ["accessory", "gift-ready"],
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
  },
  {
    id: "p8",
    slug: "toddler-cable-knit-cardigan",
    name: "Toddler Cable-Knit Cardigan",
    description:
      "A chunky cable-knit cardigan in brushed wool-blend yarn with horn buttons — the layering piece for cool mornings and golden-hour walks.",
    price: 190,
    discountPrice: 160,
    category: "Toddlers",
    subcategory: "Outerwear",
    ageGroup: "1–4 years",
    sizes: ["12M", "18M", "2T", "3T", "4T"],
    colors: ["Beige", "Sage"],
    stock: 11,
    sku: "TTC-TD-018",
    status: "active",
    weightGrams: 230,
    images: [{ url: "", alt: "Toddler cable-knit cardigan in beige" }],
    tags: ["outerwear", "sale", "layering"],
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
  },
];

export function getSampleProductBySlug(slug: string): Product | undefined {
  return sampleProducts.find((p) => p.slug === slug);
}
