// Starter catalog for the remaining products — imported once via
// Admin > Products > Import Starter Catalog. Safe to run more than once:
// the import skips any slug that already exists.

export interface SeedProduct {
  slug: string;
  name: string;
  description: string;
  price: number;
  category: string;
  ageGroup: string;
  sizes: string[];
  colors: string[];
  stock: number;
  sku: string;
  tags: string[];
  image: string;
}

const S = "12-18 months, 18-24 months, 2-3 years, 3-4 years".split(", ");

export const seedProducts: SeedProduct[] = [
  { slug: "baby-bear-paws-two-piece", name: "Baby Bear Paws Two-Piece Set", description: "A soft sky-blue long-sleeve set with a friendly bear print on top and a scattered paw-print pattern below.", price: 140, category: "Matching Sets", ageGroup: "1-3 years", sizes: S, colors: ["Sky Blue", "Navy"], stock: 20, sku: "TTC-007", tags: ["bear", "two-piece"], image: "/seed-products/ttc-007.jpg" },
  { slug: "paw-prints-two-piece", name: "Paw Prints Two-Piece Set", description: "A deep teal long-sleeve set covered in playful paw prints, with a cuddly bear graphic on the chest.", price: 140, category: "Matching Sets", ageGroup: "1-3 years", sizes: S, colors: ["Teal"], stock: 20, sku: "TTC-008", tags: ["bear", "paw print", "two-piece"], image: "/seed-products/ttc-008.jpg" },
  { slug: "happy-birds-two-piece", name: "Happy Birds Two-Piece Set", description: "A cheerful navy set with a hand-drawn bird print on top, paired with classic navy-and-white striped pants.", price: 140, category: "Matching Sets", ageGroup: "1-3 years", sizes: S, colors: ["Navy", "White"], stock: 20, sku: "TTC-009", tags: ["stripes", "two-piece"], image: "/seed-products/ttc-009.jpg" },
  { slug: "little-dino-stripe-two-piece", name: "Little Dino Stripe Two-Piece Set", description: "A sunny yellow striped top with a small dinosaur graphic, paired with solid dark green pants.", price: 140, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Yellow", "Green"], stock: 20, sku: "TTC-010", tags: ["dinosaur", "stripes", "boys"], image: "/seed-products/ttc-010.jpg" },
  { slug: "caped-hero-two-piece", name: "Caped Hero Two-Piece Set", description: "A soft grey long-sleeve set featuring a playful caped-superhero graphic, with an all-over emblem print on the pants.", price: 145, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Grey", "Black"], stock: 15, sku: "TTC-011", tags: ["superhero", "boys", "two-piece"], image: "/seed-products/ttc-011.jpg" },
  { slug: "lets-go-bear-two-piece", name: "Let's Go Bear Two-Piece Set", description: "A sporty grey set with a boxing bear character and \"let's go go go\" print, matched with an all-over bear pattern on the pants.", price: 140, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Grey"], stock: 18, sku: "TTC-012", tags: ["bear", "boys", "two-piece"], image: "/seed-products/ttc-012.jpg" },
  { slug: "happy-new-year-two-piece", name: "Happy New Year Holiday Two-Piece Set", description: "A festive cream set with reindeer, tree, and Santa graphics on top, paired with cozy red plaid pants.", price: 150, category: "Matching Sets", ageGroup: "1-3 years", sizes: S, colors: ["Cream", "Red"], stock: 15, sku: "TTC-013", tags: ["holiday", "christmas", "two-piece"], image: "/seed-products/ttc-013.jpg" },
  { slug: "cheeky-monkey-two-piece", name: "Cheeky Monkey Two-Piece Set", description: "A bright red long-sleeve top with a playful monkey graphic, paired with soft grey pants.", price: 140, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Red", "Grey"], stock: 20, sku: "TTC-014", tags: ["monkey", "two-piece"], image: "/seed-products/ttc-014.jpg" },
  { slug: "hug-me-elephant-set", name: "Hug Me Elephant Two-Piece Set", description: "A mint green short-sleeve tee with a sweet elephant graphic, paired with black-and-white grid-print shorts.", price: 120, category: "Toddlers", ageGroup: "1-3 years", sizes: S, colors: ["Mint", "White", "Black"], stock: 20, sku: "TTC-015", tags: ["elephant", "summer", "two-piece"], image: "/seed-products/ttc-015.jpg" },
  { slug: "bunny-summer-two-piece", name: "Bunny Summer Two-Piece Set", description: "A white short-sleeve tee covered in a sweet bunny print, paired with solid pink shorts.", price: 120, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["White", "Pink"], stock: 20, sku: "TTC-016", tags: ["bunny", "girls", "summer"], image: "/seed-products/ttc-016.jpg" },
  { slug: "beep-car-two-piece", name: "Beep Beep Car Two-Piece Set", description: "A light grey short-sleeve tee with a fun car-and-dinosaur graphic, matched with an all-over traffic-themed print on the shorts.", price: 120, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Grey", "Multicolor"], stock: 20, sku: "TTC-017", tags: ["car", "boys", "summer"], image: "/seed-products/ttc-017.jpg" },
  { slug: "roar-tiger-two-piece", name: "Roar Tiger Two-Piece Set", description: "A striped long-sleeve top with a friendly tiger graphic and \"Roar\" print, paired with soft grey pants.", price: 140, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["White", "Grey"], stock: 20, sku: "TTC-018", tags: ["tiger", "stripes", "boys"], image: "/seed-products/ttc-018.jpg" },
  { slug: "striped-elephant-two-piece", name: "Striped Elephant Two-Piece Set", description: "A sunny yellow long-sleeve top with a bold elephant silhouette, paired with matching striped pants.", price: 140, category: "Matching Sets", ageGroup: "1-3 years", sizes: S, colors: ["Yellow", "White"], stock: 20, sku: "TTC-019", tags: ["elephant", "stripes", "two-piece"], image: "/seed-products/ttc-019.jpg" },
  { slug: "safari-friends-two-piece", name: "Safari Friends Two-Piece Set", description: "A cheerful short-sleeve set covered in giraffes, lions, and elephants on a soft cream background.", price: 120, category: "Toddlers", ageGroup: "1-3 years", sizes: S, colors: ["Cream", "Multicolor"], stock: 20, sku: "TTC-020", tags: ["safari", "animals", "summer"], image: "/seed-products/ttc-020.jpg" },
  { slug: "love-my-daddy-two-piece", name: "I Love My Daddy Two-Piece Set", description: "A navy short-sleeve tee with a colorful \"I Love My Daddy\" print, paired with sunny yellow shorts.", price: 115, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Navy", "Yellow"], stock: 20, sku: "TTC-021", tags: ["boys", "summer"], image: "/seed-products/ttc-021.jpg" },
  { slug: "truck-two-piece", name: "Truck Two-Piece Set", description: "A light blue tee with a dump truck graphic, matched with construction-themed print shorts.", price: 120, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Light Blue"], stock: 20, sku: "TTC-022", tags: ["truck", "boys", "summer"], image: "/seed-products/ttc-022.jpg" },
  { slug: "tomato-two-piece", name: "Tomato Two-Piece Set", description: "A playful light blue tee with a smiling tomato character, paired with matching tomato-print shorts.", price: 120, category: "Toddlers", ageGroup: "1-3 years", sizes: S, colors: ["Light Blue", "White"], stock: 18, sku: "TTC-023", tags: ["fruit", "summer"], image: "/seed-products/ttc-023.jpg" },
  { slug: "hello-crocodile-two-piece", name: "Hello Crocodile Two-Piece Set", description: "A cheerful yellow-green set with a friendly crocodile print on both the top and shorts.", price: 120, category: "Toddlers", ageGroup: "1-3 years", sizes: S, colors: ["Green"], stock: 18, sku: "TTC-024", tags: ["crocodile", "summer"], image: "/seed-products/ttc-024.jpg" },
  { slug: "stripe-bear-two-piece", name: "Stripe Bear Two-Piece Set", description: "A brown-and-white striped tee with a sweet bear-face graphic, paired with matching striped shorts.", price: 120, category: "Matching Sets", ageGroup: "1-3 years", sizes: S, colors: ["Brown", "White"], stock: 20, sku: "TTC-025", tags: ["bear", "stripes", "summer"], image: "/seed-products/ttc-025.jpg" },
  { slug: "football-club-two-piece", name: "Football Club Two-Piece Set", description: "A navy tee with a playful \"Football Club\" graphic, paired with bright yellow shorts.", price: 115, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Navy", "Yellow"], stock: 20, sku: "TTC-026", tags: ["sports", "boys", "summer"], image: "/seed-products/ttc-026.jpg" },
  { slug: "shark-two-piece", name: "Shark Adventure Two-Piece Set", description: "A blue-and-yellow tee with a friendly shark graphic, paired with matching yellow shorts.", price: 120, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Blue", "Yellow"], stock: 20, sku: "TTC-027", tags: ["shark", "boys", "summer"], image: "/seed-products/ttc-027.jpg" },
  { slug: "blue-bear-two-piece", name: "Blue Bear Two-Piece Set", description: "A bold blue tee with a friendly bear graphic, paired with grey shorts featuring a matching bear print.", price: 120, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Blue", "Grey"], stock: 20, sku: "TTC-028", tags: ["bear", "boys", "summer"], image: "/seed-products/ttc-028.jpg" },
  { slug: "i-love-mom-two-piece", name: "I Love Mom Two-Piece Set", description: "A cozy taupe long-sleeve top with a heartfelt \"I Love Mom\" print, paired with red-and-white striped pants.", price: 140, category: "Matching Sets", ageGroup: "1-3 years", sizes: S, colors: ["Taupe", "Red"], stock: 20, sku: "TTC-029", tags: ["two-piece"], image: "/seed-products/ttc-029.jpg" },
  { slug: "unicorn-star-two-piece", name: "Unicorn Star Two-Piece Set", description: "A dreamy pink long-sleeve set with a magical unicorn graphic and matching crown-and-unicorn print pants.", price: 140, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["Pink"], stock: 20, sku: "TTC-030", tags: ["unicorn", "girls", "two-piece"], image: "/seed-products/ttc-030.jpg" },
  { slug: "nice-day-dino-two-piece", name: "Nice Day Dino Two-Piece Set", description: "A soft cream short-sleeve tee with a sweet dinosaur graphic, paired with matching shorts.", price: 120, category: "Toddlers", ageGroup: "1-3 years", sizes: S, colors: ["Cream", "Green"], stock: 20, sku: "TTC-031", tags: ["dinosaur", "summer"], image: "/seed-products/ttc-031.jpg" },
  { slug: "sunny-smiley-two-piece", name: "Sunny Smiley Two-Piece Set", description: "A cheerful white tee with a smiling sun graphic, paired with sky-blue shorts.", price: 115, category: "Toddlers", ageGroup: "1-3 years", sizes: S, colors: ["White", "Blue"], stock: 20, sku: "TTC-032", tags: ["summer"], image: "/seed-products/ttc-032.jpg" },
  { slug: "lets-go-play-car-two-piece", name: "Let's Go Play Car Two-Piece Set", description: "A soft grey tee with a fun car-and-road graphic, paired with matching car-print shorts.", price: 120, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Grey"], stock: 20, sku: "TTC-033", tags: ["car", "boys", "summer"], image: "/seed-products/ttc-033.jpg" },
  { slug: "yellow-dragon-stripe-two-piece", name: "Yellow Dragon Stripe Two-Piece Set", description: "A sunny yellow striped tee with a small dragon graphic, paired with solid green shorts.", price: 120, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Yellow", "Green"], stock: 20, sku: "TTC-034", tags: ["dinosaur", "stripes", "boys"], image: "/seed-products/ttc-034.jpg" },
  { slug: "toy-minibear-two-piece", name: "Toy Minibear Two-Piece Set", description: "A bright green tee with a cute teddy-bear graphic, paired with striped shorts featuring a matching bear print.", price: 120, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Green", "White"], stock: 18, sku: "TTC-035", tags: ["bear", "summer"], image: "/seed-products/ttc-035.jpg" },
  { slug: "panda-stripe-two-piece", name: "Panda Stripe Two-Piece Set", description: "A striped brown-and-white tee with a playful panda face graphic, paired with matching striped shorts.", price: 120, category: "Toddlers", ageGroup: "1-3 years", sizes: S, colors: ["Brown", "White"], stock: 18, sku: "TTC-036", tags: ["panda", "stripes", "summer"], image: "/seed-products/ttc-036.jpg" },
  { slug: "love-you-friend-two-piece", name: "Love You Friend Two-Piece Set", description: "A navy tee with a bright, friendly \"I Love You\" smiley print, paired with sunny yellow shorts.", price: 115, category: "Toddlers", ageGroup: "1-3 years", sizes: S, colors: ["Navy", "Yellow"], stock: 20, sku: "TTC-037", tags: ["summer"], image: "/seed-products/ttc-037.jpg" },
  { slug: "happy-baby-two-piece", name: "Happy Baby Two-Piece Set", description: "A rich teal tee with a sweet graphic print, paired with matching checkered-print shorts.", price: 120, category: "Toddlers", ageGroup: "1-3 years", sizes: S, colors: ["Teal", "White"], stock: 20, sku: "TTC-038", tags: ["summer"], image: "/seed-products/ttc-038.jpg" },
  { slug: "lime-smiley-tank-set", name: "Lime Smiley Tank Two-Piece Set", description: "A sunny yellow ruffle-sleeve tank with a cheerful lemon-smiley print, paired with matching lemon-print shorts.", price: 120, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["Yellow"], stock: 20, sku: "TTC-039", tags: ["girls", "summer", "tank"], image: "/seed-products/ttc-039.jpg" },
  { slug: "now-heart-tank-set", name: "Now Heart Tank Two-Piece Set", description: "A bold red ruffle-sleeve tank with a fun graphic cloud print, paired with heart-print shorts.", price: 120, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["Red"], stock: 20, sku: "TTC-040", tags: ["girls", "summer", "tank"], image: "/seed-products/ttc-040.jpg" },
  { slug: "heart-bow-tank-set", name: "Heart & Bow Tank Two-Piece Set", description: "A sweet pink ruffle-sleeve tank with a floral heart graphic, paired with strawberry-and-stripe print shorts.", price: 120, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["Pink"], stock: 20, sku: "TTC-041", tags: ["girls", "summer", "tank"], image: "/seed-products/ttc-041.jpg" },
  { slug: "unicorn-garden-tank-set", name: "Unicorn Garden Tank Two-Piece Set", description: "A delicate white ruffle-sleeve tank with a floral unicorn graphic, paired with matching unicorn-print shorts.", price: 125, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["White", "Pink"], stock: 20, sku: "TTC-042", tags: ["unicorn", "girls", "tank"], image: "/seed-products/ttc-042.jpg" },
  { slug: "cute-bunny-tank-set", name: "Cute Baby Bunny Tank Two-Piece Set", description: "A soft lilac ruffle-sleeve tank with an adorable bunny graphic, paired with matching lilac shorts.", price: 120, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["Lilac"], stock: 20, sku: "TTC-043", tags: ["bunny", "girls", "tank"], image: "/seed-products/ttc-043.jpg" },
  { slug: "flamingo-cupcake-tank-set", name: "Flamingo Cupcake Tank Two-Piece Set", description: "A pretty pink ruffle-sleeve tank with a flamingo-and-cupcake graphic, paired with matching flamingo-print shorts.", price: 120, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["Pink"], stock: 20, sku: "TTC-044", tags: ["flamingo", "girls", "tank"], image: "/seed-products/ttc-044.jpg" },
  { slug: "magic-unicorn-tank-set", name: "Magic Unicorn Tank Two-Piece Set", description: "A soft white ruffle-sleeve tank with a colorful \"Magic\" unicorn graphic, paired with matching unicorn-print shorts.", price: 125, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["White", "Blue"], stock: 20, sku: "TTC-045", tags: ["unicorn", "girls", "tank"], image: "/seed-products/ttc-045.jpg" },
  { slug: "sweet-heart-tank-set", name: "Sweet Heart Tank Two-Piece Set", description: "A soft blue ruffle-sleeve tank with a polka-dot heart graphic, paired with pink heart-print shorts.", price: 120, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["Blue", "Pink"], stock: 20, sku: "TTC-046", tags: ["girls", "tank"], image: "/seed-products/ttc-046.jpg" },
  { slug: "pretty-in-pink-flamingo-tank-set", name: "Pretty in Pink Flamingo Tank Two-Piece Set", description: "A soft lilac ruffle-sleeve tank with a chic flamingo graphic, paired with matching flamingo-print shorts.", price: 120, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["Lilac", "Pink"], stock: 20, sku: "TTC-047", tags: ["flamingo", "girls", "tank"], image: "/seed-products/ttc-047.jpg" },
  { slug: "love-cat-tank-set", name: "Love Cat Tank Two-Piece Set", description: "A sweet pink ruffle-sleeve tank with an adorable cat graphic, paired with matching cat-and-heart print shorts.", price: 120, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["Pink"], stock: 20, sku: "TTC-048", tags: ["cat", "girls", "tank"], image: "/seed-products/ttc-048.jpg" },
  { slug: "duck-two-piece", name: "Little Duck Two-Piece Set", description: "A cheerful white tee covered in a sweet duck print, paired with solid yellow shorts.", price: 115, category: "Toddlers", ageGroup: "1-3 years", sizes: S, colors: ["White", "Yellow"], stock: 20, sku: "TTC-049", tags: ["duck", "summer"], image: "/seed-products/ttc-049.jpg" },
  { slug: "good-bear-stripe-two-piece", name: "Good Bear Stripe Two-Piece Set", description: "A sunny yellow-and-white striped tee with a sweet bear graphic, paired with solid yellow shorts.", price: 115, category: "Toddlers", ageGroup: "1-3 years", sizes: S, colors: ["Yellow", "White"], stock: 20, sku: "TTC-050", tags: ["bear", "stripes", "summer"], image: "/seed-products/ttc-050.jpg" },
  { slug: "dino-cloud-two-piece", name: "Dino Cloud Two-Piece Set", description: "A soft white tee with a friendly dinosaur-and-cloud print, paired with solid dark green shorts.", price: 115, category: "Toddlers", ageGroup: "1-3 years", sizes: S, colors: ["White", "Green"], stock: 20, sku: "TTC-051", tags: ["dinosaur", "summer"], image: "/seed-products/ttc-051.jpg" },
  { slug: "pocket-stripe-two-piece", name: "Pocket Stripe Two-Piece Set", description: "A clean grey tee with a printed pocket detail, paired with grey-and-yellow striped shorts.", price: 115, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Grey", "Yellow"], stock: 20, sku: "TTC-052", tags: ["stripes", "summer"], image: "/seed-products/ttc-052.jpg" },
  { slug: "sparkle-leopard-two-piece", name: "Sparkle Leopard Two-Piece Set", description: "A soft cream tee with a sparkly heart graphic, paired with a bold leopard-print short.", price: 125, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["Cream", "Leopard"], stock: 20, sku: "TTC-053", tags: ["girls", "leopard", "summer"], image: "/seed-products/ttc-053.jpg" },
  { slug: "flamingo-moment-two-piece", name: "Flamingo Moment Two-Piece Set", description: "A soft pink tee with a romantic flamingo graphic, paired with matching tropical flamingo-print shorts.", price: 120, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["Pink"], stock: 20, sku: "TTC-054", tags: ["flamingo", "girls", "summer"], image: "/seed-products/ttc-054.jpg" },
  { slug: "hello-cats-two-piece", name: "Hello Cats Two-Piece Set", description: "A sweet pink tee with a trio of playful cat characters, paired with matching heart-print shorts.", price: 120, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["Pink", "White"], stock: 20, sku: "TTC-055", tags: ["cat", "girls", "summer"], image: "/seed-products/ttc-055.jpg" },
  { slug: "wild-dino-two-piece-a", name: "Wild Dino Two-Piece Set", description: "A sunny yellow tee with a bold \"Wild\" dinosaur graphic, paired with matching all-over dino-print shorts.", price: 120, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Yellow"], stock: 20, sku: "TTC-056", tags: ["dinosaur", "boys", "summer"], image: "/seed-products/ttc-056.jpg" },
  { slug: "wild-dino-two-piece-b", name: "Sunshine Dino Two-Piece Set", description: "A soft yellow tee covered in a friendly dinosaur print, paired with matching dino-print shorts.", price: 120, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Yellow"], stock: 20, sku: "TTC-057", tags: ["dinosaur", "boys", "summer"], image: "/seed-products/ttc-057.jpg" },
  { slug: "sky-dino-two-piece", name: "Sky Dino Two-Piece Set", description: "A soft sky-blue tee covered in a gentle dinosaur print, paired with matching print shorts.", price: 120, category: "Toddlers", ageGroup: "1-3 years", sizes: S, colors: ["Sky Blue"], stock: 20, sku: "TTC-058", tags: ["dinosaur", "summer"], image: "/seed-products/ttc-058.jpg" },
  { slug: "panda-clouds-two-piece", name: "Panda Clouds Two-Piece Set", description: "A gentle sage-green tee with a sleepy panda-and-cloud print, paired with matching shorts.", price: 120, category: "Toddlers", ageGroup: "1-3 years", sizes: S, colors: ["Sage"], stock: 20, sku: "TTC-059", tags: ["panda", "summer"], image: "/seed-products/ttc-059.jpg" },
  { slug: "pink-bunny-circle-two-piece", name: "Pink Bunny Two-Piece Set", description: "A soft pink tee with a playful bunny print, paired with matching bunny-print shorts.", price: 120, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["Pink"], stock: 20, sku: "TTC-060", tags: ["bunny", "girls", "summer"], image: "/seed-products/ttc-060.jpg" },
  { slug: "caped-hero-summer-two-piece", name: "Caped Hero Summer Two-Piece Set", description: "A crisp white tee with a playful caped-hero emblem graphic, paired with solid navy shorts.", price: 115, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["White", "Navy"], stock: 18, sku: "TTC-061", tags: ["superhero", "boys", "summer"], image: "/seed-products/ttc-061.jpg" },
  { slug: "hush-crocodile-two-piece", name: "Hush Crocodile Two-Piece Set", description: "A soft green tee with a sleepy crocodile graphic, paired with matching grey shorts.", price: 120, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Green", "Grey"], stock: 20, sku: "TTC-062", tags: ["crocodile", "boys", "summer"], image: "/seed-products/ttc-062.jpg" },
  { slug: "bunny-faces-two-piece", name: "Bunny Faces Two-Piece Set", description: "A soft white tee covered in sweet bunny faces, paired with solid pink shorts.", price: 120, category: "Baby Girls", ageGroup: "1-3 years", sizes: S, colors: ["White", "Pink"], stock: 20, sku: "TTC-063", tags: ["bunny", "girls", "summer"], image: "/seed-products/ttc-063.jpg" },
  { slug: "sleepy-pup-two-piece", name: "Sleepy Pup Two-Piece Set", description: "A cozy cream tee with a cute sleeping puppy graphic, paired with matching striped shorts.", price: 120, category: "Toddlers", ageGroup: "1-3 years", sizes: S, colors: ["Cream"], stock: 18, sku: "TTC-064", tags: ["puppy", "summer"], image: "/seed-products/ttc-064.jpg" },
  { slug: "sports-bear-two-piece", name: "Sports Bear Two-Piece Set", description: "A cream tee with a collegiate-style \"Sports Bear\" baseball graphic, paired with a paw-print plaid short.", price: 125, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Cream"], stock: 18, sku: "TTC-065", tags: ["sports", "boys", "summer"], image: "/seed-products/ttc-065.jpg" },
  { slug: "space-hero-two-piece", name: "Space Hero Two-Piece Set", description: "A cozy cream-and-blue long-sleeve set with a fun retro space-hero graphic — perfect for cooler days.", price: 145, category: "Baby Boys", ageGroup: "1-3 years", sizes: S, colors: ["Cream", "Blue"], stock: 15, sku: "TTC-066", tags: ["two-piece"], image: "/seed-products/ttc-066.jpg" },
  { slug: "teddy-friends-two-piece", name: "Teddy Friends Two-Piece Set", description: "A soft white long-sleeve set covered in a sweet teddy-bear print with striped trim.", price: 140, category: "Matching Sets", ageGroup: "1-3 years", sizes: S, colors: ["White", "Black"], stock: 20, sku: "TTC-067", tags: ["bear", "two-piece"], image: "/seed-products/ttc-067.jpg" },
  { slug: "snowman-holiday-two-piece", name: "Snowman Holiday Two-Piece Set", description: "A festive mint-green long-sleeve set with a cheerful snowman and holiday print — a sweet pick for the season.", price: 145, category: "Matching Sets", ageGroup: "1-3 years", sizes: S, colors: ["Mint"], stock: 15, sku: "TTC-068", tags: ["holiday", "christmas", "two-piece"], image: "/seed-products/ttc-068.jpg" },
];
